example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'), 
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_my_watch_list, show_xml, show_json
from mywatchlist.views import show_json_by_id, show_xml_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_my_watch_list, name='show_my_watch_list'),
    path('html/', show_my_watch_list, name='show_my_watch_list'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/',include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import deleting_task, register, login_user, logout_user, show_todolist, create_task, converting_status, deleting_task, get_todolist_json
from todolist.views import add_item_todolist
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('create-task/', create_task, name='create_task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('converting-status/<int:id>', converting_status, name='converting_status'),
    path('delete-task/<int:id>', deleting_task, name='deleting_task'),
    path('json/', get_todolist_json, name='get_todolist_json'),
    path('add/', add_item_todolist, name="add_item_todolist"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

# Create your models here.

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    return render(request, "katalog.html", context)

data_barang_katalog = CatalogItem.objects.all()
context = {
    'list_barang': data_barang_katalog,
    'namaku': 'Valencius Apriady Primayudha',
    'idku': '2106750830',
}

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
data_film = MyWatchList.objects.all()
def show_my_watch_list(request):
    have_watched = 0
    not_watch = 0
    for iterasi in data_film:
        if iterasi.watched:
            have_watched += 1
        else:
            not_watch+= 1
    if have_watched >= not_watch:
        extra_msg = "Selamat, kamu sudah banyak menonton!"
    else:
        extra_msg = "Wah, kamu masih sedikit menonton!"
        
    context = {
        'message': extra_msg,
        'list_film': data_film,
        'namaku': 'Valencius Apriady Primayudha',
        'idku': '2106750830',
    }
    return render(request, "mywatchlist.html", context)


def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from multiprocessing import context
from time import time, timezone
from urllib import response
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import todolist
from todolist.models import Task
import datetime
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.core import serializers
# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_task = Task.objects.filter(user=request.user)
    context = {
        'list_task': data_task,
        'nama': request.user,
        'last_login': request.COOKIES['last_login'],
        
    }
    return render(request, 'todolist.html', context)


def get_todolist_json(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("json", data))

@login_required(login_url='/todolist/login/')
def create_task(request):
    if request.method == 'POST':
        Task.objects.create(
            user = request.user, 
            date = timezone.now(), 
            title = request.POST.get("task"), 
            description = request.POST.get("desc"),
        )
        return HttpResponseRedirect(reverse('todolist:show_todolist'))

    return render(request, 'create_task.html', {})


def add_item_todolist(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        description = request.POST.get("description")

        new_barang = Task(user=request.user, date=timezone.now(), title=title, description=description, is_finished=False)
        new_barang.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
            response.set_cookie('last_login', str(datetime.datetime.now())) 
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response 

@login_required(login_url='/todolist/login/')
def deleting_task(request, id):
    stuff = Task.objects.get(user=request.user, id = id)
    stuff.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def converting_status(request, id):
    stuff = Task.objects.get(user=request.user, id = id)    
    stuff.is_finished = not stuff.is_finished
    stuff.save(update_fields=["is_finished"])
    return redirect('todolist:show_todolist')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, everyone!</h1>
  <h2>This is example app of Valencius's Django template</h2>
  <h3>To access other applications you may choose: </h3>
  <a href="{% url 'katalog:show_katalog' %}">Katalog</a>
  <a href="{% url 'mywatchlist:show_my_watch_list' %}">MyWatchList</a>
  <a href="{% url 'todolist:show_todolist' %}">Todolist</a>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

 {% load static %}
  <link rel="stylesheet" href="{% static 'katalog/style.css' %}">

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ namaku }} </p>

  <h5>Student ID: </h5>
  <p>{{ idku }}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

 {% load static %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{ namaku }} </p>

  <h5>Student ID: </h5>
  <p>{{ idku }}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
      <tr>
        <th>{{film.watched}}</th>
        <th>{{film.title}}</th>
        <th>{{film.rating}}</th>
        <th>{{film.release_date}}</th>
        <th>{{film.review}}</th>
      </tr>
    {% endfor %}
  </table>

  <span><h5></h5><b>Status: </b>{{message}}</span>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  
  <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.3/dist/flowbite.min.css" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/flowbite@1.5.3/dist/flowbite.js"></script>
  {% block content %}
  {% endblock content %}
</body>
</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %} 
<style>
    .flex-first {
      font-size: 250%;
    }
    .box{
        display: flex;
        align-items: center;
        justify-content: center;
    }
  </style>
<section class="vh-100" style="background-color: #e2d5de;">
<html>
<head>
</head>
    <body>
        <section class="vh-100" style="background-color: #e2d5de;">
        <div class="box">
            <div class="container mt-3">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5" id="form1">
                            <div class="form-data" v-if="!submitted">
                                
                                <form action="" method="POST" >
                                    <h5 class="text-center name"><div class="flex-first">Create Your New Task</div></h>                                
                                {% csrf_token %}
                                Title Task: <br/><input type="text" name="task" /><br/>
                                Description Content: <br/>
                                <textarea cols="35" rows="4" name="desc" ></textarea><br/>
                                <td><div class="mb-3"> <button v-on:click.stop.prevent="submit" value="Create new Task" class="btn btn-dark w-50">Submit</button> </div></td>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>


{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}


{% block meta %}

{% endblock meta %}

{% block content %}

<style>
    .flex-first {
      font-size: 250%;
    }
  </style>

<nav class="navbar bg-light">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Welcome New User!</span>
    </div>
  </nav>

<h1 class="text-center name"><div class="flex-first">Login To Access Your ToDoList!</div></h1>

<div class="container mt-3">
    <div class="row d-flex justify-content-center">
        <div class="col-md-3">
            <div class="card px-5 py-5" id="form1">
                <div class="form-data" v-if="!submitted">

                    <form method="POST" action="" ALIGN='center'>
                        {% csrf_token %}
                        <table>
                            <tr>
                                <div class="forms-inputs mb-4"><input autocomplete="off" name="username" placeholder="Username" type="text" v-model="email" v-bind:class="{'form-control':true, 'is-invalid' : !validEmail(email) && emailBlured}" v-on:blur="emailBlured = true">
                                
                            </tr>
                                    
                            <tr>
                                <div class="forms-inputs mb-4"><input autocomplete="off" name="password" placeholder="Password" type="password" v-model="password" v-bind:class="{'form-control':true, 'is-invalid' : !validPassword(password) && passwordBlured}" v-on:blur="passwordBlured = true">
                            </tr>

                            <tr>
                                <td></td>
                                <div class="mb-3"> <button v-on:click.stop.prevent="submit" value="Login" class="btn btn-dark w-100">Login</button> </div>
                            </tr>
                        </table>
                    </form>
                    {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li> {{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}     
        
                    Belum mempunyai akun?<br/> Click -> <a href="{% url 'todolist:register' %}">Buat Akun</a>
                </div>
            </div>
        </div>
    </div>
</div>
    

</div>



{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<style>
    .flex-first {
      font-size: 250%;
    }
  </style>

<h1 class="text-center name"><div class="flex-first">Formulir Registrasi</div></h1>


<div class="container mt-3">
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div class="card px-5 py-5" id="form1">
                <div class="form-data" v-if="!submitted">
                        <form method="POST" >  
                            {% csrf_token %}  
                            <table>  
                                {{ form.as_table }}  
                                <tr>  
                                    <td></td>

                                    <td><div class="mb-3"> <button v-on:click.stop.prevent="submit" value="Daftar" class="btn btn-dark w-100">Submit</button> </div></td>
                                </tr>  
                            </table>  
                        </form>

                    {% if messages %}  
                        <ul>   
                            {% for message in messages %}  
                                <li>{{ message }}</li>  
                                {% endfor %}  
                        </ul>   
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>  



{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
 {% load static %}

 <nav class="navbar bg-light">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1"><b>Welcome!</b><img src="{% static 'todolist/images/user1.jpg' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
      {{nama}}</span>
    <button class="btn btn-outline-success me-2" type="button"><a href="{% url 'todolist:logout' %}">Logout</a>
    </button>
  </div>
</nav>

<div class="d-flex justify-content-center">
    <div class="h2">
      <h1>To Do List</h1>
    </div>
</div>
<style>
  .flex-first {
    display: flex;
    justify-content: center;
    margin: 10px;
  }
  .flex-second {
    display: flex;
    justify-content: center;
    margin: 25px; 
  }
  .flex-third {
    display: flex;
    flex-direction: row;
    align-self: flex-end;
    justify-content: flex-start;
  }
  .cards:hover{
    box-shadow: 5px 6px 6px 2px #e9ecef;
    transform: scale(1.1);
  }
</style>
<div class="flex-second">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Create Task</button>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create Your New Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="formnewtask">
          {% csrf_token %}
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Title</label>
            <input type="text" class="form-control" id="title" name ="title">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description</label>
            <textarea class="form-control" id="description" name="description"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="taskbutton"  data-bs-dismiss="modal">Save New Task</button>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div id="containCards">

  </div>
</div>

<div class="flex-second">
  <h3>Sesi terakhir login: {{ last_login }}</h3>
</div>
<div class="flex-second">
  <div class="flex-third">
    <button><a href="{% url 'todolist:logout' %}"class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Logout</a></button>
  </div>
</div>

<script>
  $(document).ready(function(){
    refreshTodolist();
  });

  async function getTodolist() {
    return fetch("{% url 'todolist:get_todolist_json' %}").then((res) => res.json())
  }

  async function refreshTodolist() {
        document.getElementById("containCards").innerHTML = ""
        const todolist = await getTodolist()
        let htmlString = ``
        todolist.forEach((item) => {
          htmlString += `\n
          <tr>
            <div class="flex-first">
              <div class="cards">
                <div class="p-6 max-w-sm bg-white rounded-lg border border-gray-800 shadow-md dark:bg-gray-800 dark:border-gray-700 card text-center">
                    <div class="flex-first">
                      <h1 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">${item.fields.title}</h1>
                      {% if task.is_finished %} <h1>&#9989;</h1> {% else %} <h1>&#10060;</h1> {% endif %}
                    </div>
                    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">${item.fields.description}</p>
                    <h6>${item.fields.date}</h6>
                </div>
              </div>
            </div>
          </tr>
          ` 
        })
        
        document.getElementById("containCards").innerHTML = htmlString
  }

  function addTodolist() {
    fetch("{% url 'todolist:add_item_todolist' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#formnewtask'))
      }).then(refreshTodolist)
    return false
  }
  document.getElementById("taskbutton").onclick = addTodolist
  refreshTodolist()
</script>

 {% endblock content %}